from django.shortcuts import render
import random
from django.http import HttpResponse

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer, ChatterBotCorpusTrainer

from . import conversation

bot = ChatBot(
    "chatbot",
    read_only=False,
    # storage_adapter="chatterbot.storage.SQLStorageAdapter",
    logic_adapters=[
        {
            "import_path": "chatterbot.logic.BestMatch",
            "default_response": "Sorry, Unable to answer to your question as an AI model. And Lot more to learn!",
            "maximum_similarity_threshold": 0.99,
        }
    ],
)


chatterBotCorpusTrainer = ChatterBotCorpusTrainer(bot)
chatterBotCorpusTrainer.train("chatterbot.corpus.english")

list_trainer = ListTrainer(bot)
list_trainer.train(conversation.list_to_train)


# Create your views here.


def index(request):
    return render(request, "bot/index.html")


def specific(request):
    return HttpResponse("Specific")


# def article(request, article_id):
#     # return HttpResponse(article_id)
#     return render(request, "bot/index.html", {"article_id": article_id})

# Keyword Matching
GREETING_INPUTS = (
    "hello",
    "hi",
    "greetings",
    "sup",
    "what's up",
    "hey",
)
GREETING_RESPONSES = [
    "hi",
    "hey",
    "*nods*",
    "hi there",
    "hello",
    "I am glad! You are talking to me",
]


def greeting(sentence):
    """If user's input is a greeting, return a greeting response"""
    for word in sentence.split():
        if word.lower() in GREETING_INPUTS:
            return random.choice(GREETING_RESPONSES)


def getResponse(request):
    userMessage = request.GET.get("userMessage")
    user_response = userMessage.lower()

    if user_response == "thanks" or user_response == "thank you":
        return HttpResponse(str("You are welcome.."))

    # Get the latest response generated by the ChatBot

    chatResponse = str(bot.get_response(userMessage))
    list_trainer.train([userMessage, chatResponse])

    return HttpResponse(chatResponse)
